CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255),
    person_id VARCHAR(12) UNIQUE NOT NULL,
    uuid VARCHAR(36) UNIQUE NOT NULL
);
